import React from "react";
import { base44 } from "@/api/base44Client";
import { useQuery } from "@tanstack/react-query";
import StaffPerformance from "@/components/reports/StaffPerformance";

export default function StaffSales() {
  const { data: sales = [], isLoading } = useQuery({
    queryKey: ["sales"],
    queryFn: () => base44.entities.Sale.list(),
  });

  const { data: user } = useQuery({ queryKey: ["me"], queryFn: () => base44.auth.me(), staleTime: 5 * 60 * 1000 });
  const { data: companies = [] } = useQuery({
    queryKey: ["companies"],
    queryFn: () => base44.entities.Company.list(),
  });

  const company = (user && companies.find(c => c.id === (user.company_id || user.tenant_id))) || companies[0];

  if (isLoading) {
    return (
      <div className="p-6 flex items-center justify-center min-h-[60vh]">
        <div className="w-8 h-8 border-4 border-slate-200 border-t-blue-600 rounded-full animate-spin" />
      </div>
    );
  }

  return (
    <div className="p-4 md:p-6 lg:p-8">
      <div className="mb-4">
        <h1 className="text-2xl md:text-3xl font-bold text-slate-900">Staff Sales Dashboard</h1>
        <p className="text-slate-500 mt-1">Track total sales generated by each employee to manage performance and incentives</p>
      </div>
      <StaffPerformance
        sales={sales}
        currency={company?.currency || "NGN"}
        showSymbol={company?.show_currency_symbol}
      />
    </div>
  );
}